using System.Collections.Generic;
using System.Windows.Media;

namespace AsystentZOOM.VM.Common
{
    public static class ColorsHelper
    {
        public static Dictionary<Color, string> ColorsDictionary = new Dictionary<Color, string>
            {
                { Colors.AliceBlue,             "Alice Blue"                },
                { Colors.LightSalmon,           "Lekki łosoś"               },
                { Colors.AntiqueWhite,          "Antyczna biel"             },
                { Colors.LightSeaGreen,         "Jasnozielony"              },
                { Colors.LightSkyBlue,          "Jasnoniebieski"            },
                { Colors.Aquamarine,            "Akwamaryn"                 },
                { Colors.LightSlateGray,        "Jasnoszary łupek"          },
                { Colors.LightSteelBlue,        "Jasnoniebieski stalowy"    },
                { Colors.Beige,                 "Beżowy"                    },
                { Colors.LightYellow,           "Jasny żółty"               },
                { Colors.Bisque,                "For"                       },
                { Colors.Lime,                  "Limonka"                   },
                { Colors.Black,                 "Czarny"                    },
                { Colors.LimeGreen,             "Limonkowy"                 },
                { Colors.BlanchedAlmond,        "Blanszowany migdał"        },
                { Colors.Linen,                 "Bielizna"                  },
                { Colors.Blue,                  "Niebieski"                 },
                { Colors.BlueViolet,            "Niebiesko-fioletowy"       },
                { Colors.Maroon,                "Kasztanowaty"              },
                { Colors.Brown,                 "Brązowy"                   },
                { Colors.MediumAquamarine,      "Średni akwamaryn"          },
                { Colors.BurlyWood,             "Grube drewno"              },
                { Colors.MediumBlue,            "Średni niebieski"          },
                { Colors.CadetBlue,             "Niebieski kadet"           },
                { Colors.MediumOrchid,          "Średnia orchidea"          },
                { Colors.Chartreuse,            "Chartreuse"                },
                { Colors.MediumPurple,          "Średni fiolet"             },
                { Colors.Chocolate,             "Czekolada"                 },
                { Colors.MediumSeaGreen,        "Średni zielony morski"     },
                { Colors.Coral,                 "Koral"                     },
                { Colors.MediumSlateBlue,       "Średni łupkowy niebieski"  },
                { Colors.CornflowerBlue,        "Chabrowy"                  },
                { Colors.MediumSpringGreen,     "Średni wiosenny zielony"   },
                { Colors.Cornsilk,              "Cornsilk"                  },
                { Colors.MediumTurquoise,       "Średni turkus"             },
                { Colors.Crimson,               "Karmazynowy"               },
                { Colors.MediumVioletRed,       "Średni fioletowo-czerwony" },
                { Colors.Cyan,                  "Cyjan"                     },
                { Colors.MidnightBlue,          "Niebieska północ"          },
                { Colors.DarkBlue,              "Ciemny niebieski"          },
                { Colors.MintCream,             "Krem miętowy"              },
                { Colors.DarkCyan,              "Ciemnobłękitny"            },
                { Colors.MistyRose,             "Mglista róża"              },
                { Colors.DarkGoldenrod,         "Ciemna nawłoć"             },
                { Colors.Moccasin,              "Mokasyn"                   },
                { Colors.DarkGray,              "Ciemny szary"              },
                { Colors.NavajoWhite,           "Navajo biały"              },
                { Colors.DarkGreen,             "Ciemnozielony"             },
                { Colors.Navy,                  "Marynarka wojenna"         },
                { Colors.DarkKhaki,             "Ciemny khaki"              },
                { Colors.OldLace,               "Stare koronki"             },
                { Colors.DarkMagenta,           "Ciemnopurpurowy"           },
                { Colors.Olive,                 "Oliwa"                     },
                { Colors.DarkOliveGreen,        "Ciemnozielony oliwkowy"    },
                { Colors.OliveDrab,             "Oliwkowy"                  },
                { Colors.DarkOrange,            "Ciemna pomarańcza"         },
                { Colors.Orange,                "Pomarańczowy"              },
                { Colors.DarkOrchid,            "Ciemna orchidea"           },
                { Colors.OrangeRed,             "Pomarańczowy czerwony"     },
                { Colors.DarkSalmon,            "Ciemny łosoś"              },
                { Colors.PaleGoldenrod,         "Blada nawłoć"              },
                { Colors.DarkSeaGreen,          "Ciemnozielony morski"      },
                { Colors.PaleGreen,             "Bladozielony"              },
                { Colors.DarkSlateBlue,         "Ciemnoniebieski"           },
                { Colors.PaleTurquoise,         "Blady turkus"              },
                { Colors.DarkSlateGray,         "Ciemnoszary łupek"         },
                { Colors.PaleVioletRed,         "Blady fioletowo-czerwony"  },
                { Colors.DarkTurquoise,         "Ciemny turkus"             },
                { Colors.PapayaWhip,            "Bat papai"                 },
                { Colors.DarkViolet,            "Ciemnofioletowy"           },
                { Colors.PeachPuff,             "Ptyś brzoskwiniowy"        },
                { Colors.DeepPink,              "Głęboki róż"               },
                { Colors.Peru,                  "Peru"                      },
                { Colors.DeepSkyBlue,           "Głęboki błękit nieba"      },
                { Colors.Pink,                  "Różowy"                    },
                { Colors.DimGray,               "Ciemnoszary"               },
                { Colors.Plum,                  "Śliwka"                    },
                { Colors.DodgerBlue,            "Dodger Blue"               },
                { Colors.PowderBlue,            "Pudrowy niebieski"         },
                { Colors.Firebrick,             "Szamot"                    },
                { Colors.Purple,                "Fioletowy"                 },
                { Colors.FloralWhite,           "Kwiatowy biały"            },
                { Colors.Red,                   "Czerwony"                  },
                { Colors.ForestGreen,           "Zielony las"               },
                { Colors.RosyBrown,             "Różowo-brązowy"            },
                { Colors.Fuchsia,               "Fuksja"                    },
                { Colors.RoyalBlue,             "Królewski niebieski"       },
                { Colors.Gainsboro,             "Gainsboro"                 },
                { Colors.SaddleBrown,           "Brązowe siodło"            },
                { Colors.GhostWhite,            "Ghost white"               },
                { Colors.Salmon,                "Łosoś"                     },
                { Colors.Gold,                  "Złoto"                     },
                { Colors.SandyBrown,            "Piaskowy brąz"             },
                { Colors.Goldenrod,             "Nawłoć"                    },
                { Colors.SeaGreen,              "Zielone morze"             },
                { Colors.Gray,                  "Szary"                     },
                { Colors.SeaShell,              "Muszla morska"             },
                { Colors.Green,                 "Zielony"                   },
                { Colors.Sienna,                "Sjena"                     },
                { Colors.GreenYellow,           "Zielony żółty"             },
                { Colors.Silver,                "Srebro"                    },
                { Colors.Honeydew,              "Honeydew"                  },
                { Colors.SkyBlue,               "Niebieskie niebo"          },
                { Colors.HotPink,               "Gorący róż"                },
                { Colors.SlateBlue,             "Odcień niebieskiego"       },
                { Colors.IndianRed,             "Czerwień indyjska"         },
                { Colors.SlateGray,             "Popielaty"                 },
                { Colors.Indigo,                "Indygo"                    },
                { Colors.Snow,                  "Śnieg"                     },
                { Colors.Ivory,                 "Kość słoniowa"             },
                { Colors.SpringGreen,           "Wiosenna zieleń"           },
                { Colors.Khaki,                 "Khaki"                     },
                { Colors.SteelBlue,             "Stalowo-niebieski"         },
                { Colors.Lavender,              "Lawenda"                   },
                { Colors.Tan,                   "Dębnik"                    },
                { Colors.LavenderBlush,         "Róż lawendowy"             },
                { Colors.Teal,                  "Cyraneczka"                },
                { Colors.LawnGreen,             "Zielony trawnik"           },
                { Colors.Thistle,               "Oset"                      },
                { Colors.LemonChiffon,          "Szyfon cytrynowy"          },
                { Colors.Tomato,                "Pomidor"                   },
                { Colors.LightBlue,             "Jasny niebieski"           },
                { Colors.Turquoise,             "Turkus"                    },
                { Colors.LightCoral,            "Jasny koral"               },
                { Colors.Violet,                "Fioletowy"                 },
                { Colors.LightCyan,             "Jasnobłękitny"             },
                { Colors.Wheat,                 "Pszenica"                  },
                { Colors.LightGoldenrodYellow,  "Jasnożółty nawłoci"        },
                { Colors.White,                 "Biały"                     },
                { Colors.LightGreen,            "Jasnozielony"              },
                { Colors.WhiteSmoke,            "Biały dym"                 },
                { Colors.LightGray,             "Jasny szary"               },
                { Colors.Yellow,                "Żółty"                     },
                { Colors.LightPink,             "Jasnoróżowy"               },
                { Colors.YellowGreen,           "Żółty zielony "            }
            };
    }
}
